#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/sdk:6.0
LABEL author="Noman5237"

ENV ASPNETCORE_URLS=http://*:5010
ENV DOT_NET_USE_POLLING_FILE_WATCHER=1

WORKDIR /app
EXPOSE 5010
ENTRYPOINT ["dotnet", "bin/Debug/net6.0/CourseManagementSystem.dll"]