version: "3.8"

services:
  web-debug:
    network_mode: "host"
    build:
      context: .
      dockerfile: docker/web/Dockerfile-Debug
    volumes:
      - type: bind
        source: .
        target: /app
    depends_on:
      - db

  web:
    network_mode: "host"
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    volumes:
      - type: bind
        source: .
        target: /app
    depends_on:
      - db

  db:
    network_mode: "host"
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    volumes:
      - type: volume
        source: mssql-data
        target: /var/opt/mssql

volumes:
  mssql-data: